-- ============================================================================
-- Copyright (C) 2030	 Thibault FOUCART    <support@ptibogxiv.net>
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program. If not, see <http://www.gnu.org/licenses/>.
--
-- ===========================================================================

--ALTER TABLE llx_adherent_consumption ADD INDEX uk_adherent_consumption_fk_facture (fk_facture);
--ALTER TABLE llx_discountprice_product ADD CONSTRAINT fk_discountprice_product_fk_product 	FOREIGN KEY (fk_product)  REFERENCES llx_product (rowid) ON DELETE RESTRICT ON UPDATE NO ACTION;
